apiVersion: v1
kind: Service
metadata:
  name: buku
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8084
  selector:
    app: buku
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buku
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buku
  template:
    metadata:
      labels:
        app: buku
    spec:
      containers:
      - name: buku
        image: itsanla/buku:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_URL
          value: "http://eureka/eureka"
        - name: CQRS_SERVICE_URL
          value: "http://cqrs"
        - name: LOGSTASH_HOST
          value: "logstash"
        - name: LOGSTASH_PORT
          value: "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
