apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8761
    nodePort: 30761
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: itsanla/eureka:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_APPLICATION_NAME
          value: "eureka-server"
        - name: SERVER_PORT
          value: "8761"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
