server:
  port: 9000

spring:
  application:
    name: API-GATEWAY-MARKETPLACE
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: PRODUK-SERVICE
            uri: http://produk
            predicates:
            - Path=/api/produk/**
          - id: PELANGGAN-SERVICE
            uri: http://pelanggan
            predicates:
            - Path=/api/pelanggan/**
          - id: ORDER-SERVICE
            uri: http://order
            predicates:
            - Path=/api/order/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost